# Configuration for welcome - https://github.com/behaviorbot/welcome

newIssueWelcomeComment: >
  Thanks for opening your first issue at **The Grindhouse**™ ! Make sure to Keep Grinding™ ! 🫡

newPRWelcomeComment: >
  Thanks for opening this pull request! Please check out our Great Grinding Guidelines™ ! 🫡

firstPRMergeComment: >
  **May the Grind never end**™ ! 🫡
